### ISSUE TITLE
expected type re: c_void

### ISSUE THREAD

**Issue by AndyGauge** [rust-lang/backtrace-rs#200]
https://github.com/rust-lang-nursery/error-chain/issues/263
I'm using Rust 1.25 in travis and received an error.

note: expected type `core::option::Option<*mut libc::c_void>`
               found type `core::option::Option<*mut std::os::raw::c_void>`

**Comment by alexcrichton** [comment]
I'm sort of lost in the jungle of `c_void` within this crate and all the version compatibility whatnots unfortunately. I'd be fine taking a patch to fix this, but I think I'm unlikely to dedicate time to fixing this.

**Comment by AndyGauge** [comment]
I'm confused why version = "0.3.3" is downloading version "0.3.30"  Is there a semver bug?

**Comment by AndyGauge** [comment]
Nevermind, I just read https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

**Comment by alexcrichton** [comment]
I'm going to close this since the minimum required version for this crate is now 1.32.0
