### ISSUE TITLE
Confused about the versions

### ISSUE THREAD

**Issue by yangby-cryptape** [rust-lang/backtrace-rs#201]
We use [dependabot](https://github.com/marketplace/dependabot-preview) for our project. Recently, the bot noticed us frequently, because `backtrace` has bumped a lot of versions:

- Revert "Compat with 1.25.0"
- Bump to 0.3.30
- Compat with 1.25.0
- Bump to 0.3.29
- ... ...
- Revert "Compat with 1.25.0"
- Bump to 0.3.28
- Compat with 1.25.0
- Bump to 0.3.27
- ... ...
- Revert "Compat with 1.25.0"
- Bump to 0.3.26
- Compat with 1.25.0
- Bump to 0.3.25
- ... ...
- Revert "Compat with 1.25.0"
- Bump to 0.3.24
- Compat with 1.25.0
- Bump to 0.3.23
- ... ...
- Revert "Compat with 1.25.0"
- Bump to 0.3.22
- Compat with 1.25.0
- Bump to 0.3.21
- ... ...
- Revert "Compat with 1.25.0"
- Bump to 0.3.20
- Compat with 1.25.0
- Bump to 0.3.19

I'm a little confused. I have read the changes of the commit `Compat with 1.25.0`, only 10 deletions, but I still don't understand if it works and why need the revert.

Which version is more stable? Are they all experiment, or we can just distinguish between stable and experiment from parity of the last version number?

Thanks!

**Comment by alexcrichton** [comment]
This is something I've been doing after integrating with the standard library to avoid increasing the minimum supported version of this crate, but 1.25.0 is broken for other reasons so I'll probably stop doing this and just require 1.32.0 from now on.

In any case nothing is more unstable than the rest, just an attempt by me to preserve compatibility which I'll probably stop doing now.
