### ISSUE TITLE
Handling minimum supported Rust version changes

### ISSUE THREAD

**Issue by chrisduerr** [rust-lang/backtrace-rs#211]
I've seen a previous PR that would indicate to me that the minimum supported Rust version is somewhat considered [here](https://github.com/rust-lang/backtrace-rs/pull/137). However the 0.3.31 release bumped the minimum required Rust version above 1.32.0 on Windows (1.32 is currently the supported version by Ubuntu).

Intentionally bumping the minimum required Rust version seems like a breaking change to me, though I'm not sure if that guarantee is provided with backtrace-rs.

Is there any desire to add support for Rust versions before 1.32.0 or explicitly mark releases as breaking when the minimum supported Rust version changes?

The change in question seems to be the use of the new `target_vendor = "uwp"` annotation.

**Comment by alexcrichton** [comment]
Thanks for the report! This crate now requires 1.32.0 for a number of reasons, and it's not considered a breaking change if the new minimum version is at least 2 stable versions old.

**Comment by chrisduerr** [comment]
Thanks for the response. I'd just like to clarify that this does **not** build on 1.32.0. I think the `target_vendor = "uwp"` requires at least 1.33.0.

This still does not make this a breaking change, since the latest stable version is 1.35.0, but I just wanted to clarify that this currently does not build with the Rust version shipped on Ubuntu (but the "breaking change" is purely limited to Windows, so technically on Ubuntu the 1.32.0 release should still work).

**Comment by alexcrichton** [comment]
Yeah getting the same version working everywhere on all platforms isn't always easy, but PRs are welcome to fix the compat for platforms which don't build on 1.32.0
