### ISSUE TITLE
miniz-sys won't compile under Jenkins, but does from command line

### ISSUE THREAD

**Issue by swilcox3** [rust-lang/backtrace-rs#243]
This one's weird.  I can compile this just fine from cmd, but when I try to run a build with Jenkins on the same machine I get this error:

info: using existing install for 'stable-i686-pc-windows-msvc'
info: default toolchain set to 'stable-i686-pc-windows-msvc'

  stable-i686-pc-windows-msvc unchanged - rustc 1.37.0 (eae3437df 2019-08-13)

   Compiling failure_derive v0.1.5
   Compiling serde v1.0.91
   Compiling structopt v0.2.15
   Compiling actix-threadpool v0.1.1
   Compiling brotli-sys v0.3.2
   Compiling miniz-sys v0.1.12
   Compiling ring v0.14.6
   Compiling backtrace-sys v0.1.28
error: failed to run custom build command for `miniz-sys v0.1.12`

Caused by:
  process didn't exit successfully: `D:\Jenkins\workspace\ProjectSharingServerPrototype\target\release\build\miniz-sys-bdef2981c53970d6\build-script-build` (exit code: 1)
--- stdout
NUM_JOBS = Some("8")
TARGET = Some("i686-pc-windows-msvc")
OPT_LEVEL = Some("3")
HOST = Some("i686-pc-windows-msvc")
CC_i686-pc-windows-msvc = None
CC_i686_pc_windows_msvc = None
HOST_CC = None
CC = None
CFLAGS_i686-pc-windows-msvc = None
CFLAGS_i686_pc_windows_msvc = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
DEBUG = Some("true")
running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x86\\cl.exe" "/nologo" "/MD" "/O2" "/Z7" "/DMINIZ_NO_STDIO" "/DMINIZ_NO_ARCHIVE_APIS" "/DMINIZ_NO_ARCHIVE_WRITING_APIS" "/DMINIZ_NO_TIME" "/DMINIZ_NO_ZLIB_COMPATIBLE_NAMES" "/FoD:\\Jenkins\\workspace\\ProjectSharingServerPrototype\\target\\release\\build\\miniz-sys-784ed12de714a129\\out\\miniz.o" "/c" "miniz.c"
miniz.c
c1: fatal error C1083: Cannot open source file: 'miniz.c': No such file or directory
exit code: 2

--- stderr

error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x86\\cl.exe" "/nologo" "/MD" "/O2" "/Z7" "/DMINIZ_NO_STDIO" "/DMINIZ_NO_ARCHIVE_APIS" "/DMINIZ_NO_ARCHIVE_WRITING_APIS" "/DMINIZ_NO_TIME" "/DMINIZ_NO_ZLIB_COMPATIBLE_NAMES" "/FoD:\\Jenkins\\workspace\\ProjectSharingServerPrototype\\target\\release\\build\\miniz-sys-784ed12de714a129\\out\\miniz.o" "/c" "miniz.c" with args "cl.exe" did not execute successfully (status code exit code: 2).

I've checked the PATH, and it's the same from both cmd and Jenkins.  Using "Windows Batch command" instead of Python in Jenkins produces the same results.  
I know this is probably a Jenkins config issue over a problem with backtrace, but can you point me in the right direction as to what the issue could be?

**Comment by alexcrichton** [comment]
Thanks for the report! I think though that this is on the wrong repository since this repository doesn't have miniz.c
