### ISSUE TITLE
Support column information

### ISSUE THREAD

**Issue by est31** [rust-lang/backtrace-rs#257]
Right now, `backtrace::Symbol` contains information about line and file name. This is all that libbacktrace supplies. However, gimli supports reading column information as well. `Symbol` should get a function `column(&self) -> Option<u32>` that, if gimli is being used, returns the column, otherwise None.

**Comment by retep998** [comment]
Note that Windows dbghelp also provides column numbers, although dbghelp calls it "displacement". Most of the functions that are called which provide the line number *also* provide the displacement but that parameter is currently ignored.

**Comment by est31** [comment]
@retep998 good point, but note that currently rustc doesn't emit column information on windows. It sets them to zero because emitting them would create bad effects with VS studio. See https://github.com/rust-lang/rust/issues/42921

If LLVM gained an API to specify a full span containing start and end positions, one could think about enabling it again (or if the VS studio bugs got fixed, idk maybe by now they are).

**Comment by eggyal** [comment]
Not sure whether the bugs are fixed yet in MS debuggers, but as at writing [Clang still omits column info for MSVC targets](https://github.com/llvm/llvm-project/blob/master/clang/lib/Driver/ToolChains/Clang.cpp#L3747-L3756).
