### ISSUE TITLE
Issue in cross compiling the backtrace-sys crate for arm cortex. link.h file not found.

### ISSUE THREAD

**Issue by amittewari22** [rust-lang/backtrace-rs#259]
Hi , I am facing same issue as people logged earlier. 
**Though all other crates compiles correctly with arm toolchain.**
Toolchain is correctly updated in cargo/Config and PATH.
Though link.h if not found "HAVE_DL_ITERATE_PHDR" must have been disabled but that didn't happen.
This more looks like issue in libbacktrace compilation unit to skip symbolic backtraces if link.h not found.

I am using gcc-arm-none-eabi-8-2019-q3-update toolchain , which is latest.
Please see if its some core issue.

Details

$ cargo build
Compiling backtrace-sys v0.1.32
error: failed to run custom build command for backtrace-sys v0.1.32

Caused by:
process didn't exit successfully: backtrace-sys-4e674d497ecbb273/build-script-build (exit code: 1)
--- stdout
cargo:rustc-cfg=rbt
TARGET = Some("thumbv7em-none-eabihf")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-apple-darwin")
CC_thumbv7em-none-eabihf = None
CC_thumbv7em_none_eabihf = None
TARGET_CC = None
CC = None
CROSS_COMPILE = None
CFLAGS_thumbv7em-none-eabihf = None
CFLAGS_thumbv7em_none_eabihf = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
CARGO_CFG_TARGET_FEATURE = Some("dsp,mclass,v5te,v6,v6k,v6t2,v7")

error occurred: Command "arm-none-eabi-gcc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-mthumb" "-mfloat-abi=hard" "-march=armv7e-m" "-mfpu=fpv4-sp-d16" "-I" "src/libbacktrace" ""-fvisibility=hidden" "-DBACKTRACE_ELF_SIZE=32" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1"

cargo:warning=src/libbacktrace/elf.c:43:10: fatal error: link.h: No such file or directory
cargo:warning= #include <link.h>
cargo:warning= ^~~~~~~~
cargo:warning=compilation terminated.
exit code: 1

--- stderr

**Comment by amittewari22** [comment]
Hello Even though I disable via build.rs build.define("HAVE_DL_ITERATE_PHDR", "0"); 
 "-DHAVE_DL_ITERATE_PHDR=0" can be verified in command output.
 Still the libbacktrace/elf.c Is looking out for link.h , which ideally it should not.
#ifdef HAVE_DL_ITERATE_PHDR
#include <link.h>
#endif

Please unblock if any hints.

**Comment by alexcrichton** [comment]
Thanks for the report! This looks like a misconfigured C compiler, however. This crate can't ensure that the C compiler is set up right and you'll need to make sure all the requisite headers are present for your platform.
