### ISSUE TITLE
windows XP support

### ISSUE THREAD

**Issue by lynnux** [rust-lang/backtrace-rs#262]
Hi, I'm the author of https://github.com/lynnux/xpsupport, you can see there are several hooks to make sure the exe running ok on windows XP. But recently I received an issue about the project that gnu verion build can't run on XP.
I'v debugged and find out the main problem are caused by backtrace, the gnu version need a new windows API `QueryFullProcessImageNameA` to run, code is here:
https://github.com/rust-lang/backtrace-rs/blob/d153f36cb958881c43151d74af0f4492fb8cb32d/src/symbolize/libbacktrace.rs#L387. So, will you please check the symbol `QueryFullProcessImageNameA` of kernel32.dll, if there does not have, using other API like `GetProcessImageFileNameA ` instead ?
I also check out the msvc build, it seems not use `QueryFullProcessImageNameA`, but when I use the code in my test:
```
extern crate backtrace;
use backtrace::Backtrace;
fn main() {
    let bt = Backtrace::new();
    // do_some_work();
    println!("{:?}", bt);
}
```
It will panic, and I find out that msvc using dbghelp.dll to backtrace, it call `DBGHELP.SymInitializeW().unwrap()(GetCurrentProcess(), ptr::null_mut(), TRUE)`,(https://github.com/rust-lang/backtrace-rs/blob/09a4786a48cb12dcbee6d25f62d0759450f409a6/src/dbghelp.rs#L357), but the version of dbghelp.dll on XP lack this API. After I put a new version of dbghelp.dll with exe, which has SymInitializeW, it runs OK! I checked there has `SymInitialize` in old version of dbghelp.dll, so will you please check if there not has `SymInitializeW`,  call `SymInitialize` instead?

**Comment by alexcrichton** [comment]
Sounds reasonable to me to do! I don't mind taking PRs for XP support but I unfortunately don't have time to work on the PRs myself.

**Comment by lynnux** [comment]
Since [pr](https://github.com/rust-lang/backtrace-rs/pull/263) has been merged, the gnu version should be ok.
the msvc build use dbghelp rather than libbacktrace, but the dbhelp.dll on XP lack those functions:

SymInitializeW
SymFromAddrW
SymGetLineFromAddrW64
SymFromInlineContextW
SymGetLineFromInlineContextW

it seems a lot work to do, the easy solution for msvc build is to combined a newer version of dbghelp.dll with exe on XP if you using backtrace (like set RUST_BACKTRACE=1 when panic)
