### ISSUE TITLE
Avoid dependency on CC crate by default

### ISSUE THREAD

**Issue by awakecoding** [rust-lang/backtrace-rs#275]
We have a complex cross-platform project that we build for Windows/macOS/Linux/Android/iOS where *all* C/C++ dependencies are prebuilt and packaged through conan.io packages with strict compilation options. With this in mind, we try to enforce builds where the "cc" crate is never called because of the lack of control over the build process and compilation options. We've patched many crates to modify the build.rs script to automatically import a prebuilt conan package using conan-rs.

We've had many CI build failures recently due to the backtrace-sys crate building some C files from libbacktrace. We originally had build failures in Windows and Android. It turned out we had some issues with our Windows container for CI builds, which we fixed, but we still have issues with Android builds when libbacktrace is built. I suspect we may need to inject additional environment variables such as ANDROID_NDK, but I'd like to avoid such things as much as possible.

To work around the issue, we made a github clone of this repo and made simple modification that removes the "libbacktrace" from the default (default = ["std", "libunwind", "dladdr", "dbghelp"]). We then add a patch line to our Cargo.toml files like this:

[patch.crates-io]
backtrace = { git = "https://github.com/Devolutions/backtrace-rs", branch = "wayk" }

This works as long as none of the dependencies we use that also import backtrace in some way don't require libbacktrace, which is our case. This avoids having to prebuilt the corresponding C files because they just don't need to be built and we aren't using this specific feature ourselves.

However, the Cargo.toml patch has a problem: whenever a new version of backtrace is published, cargo will tend to select a version newer than the one on our branch, and will therefore select the unpatched version from crates.io, breaking our CI builds again. We have to rebase our branch and update old Cargo.lock files because the commit it changed again.

We therefore need to either give up building all C code ourselves, or we need to figure out a reliable way to patch external crates without facing the problem of newer unpatched versions getting picked up by cargo. It's a relatively benign patch, there must be a better way to handle such overrides.

As for giving up and letting it build C code, what would I be missing for android? Should I inject additional environment variables pointing to the android ndk? Our cmake-based projects build fine with the android cmake toolchain files.

**Comment by awakecoding** [comment]
Here is a sample build error for Android that we have in our CI environment:

`  error: failed to run custom build command for `backtrace-sys v0.1.32`
  
  Caused by:
    process didn't exit successfully: `/__w/8/s/platform/Android/app/.cxx/cmake/release/armeabi-v7a/libwayk/rust/release/build/backtrace-sys-531eaebf39a919bf/build-script-build` (exit code: 1)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("arm-linux-androideabi")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_arm-linux-androideabi = None
  CC_arm_linux_androideabi = None
  TARGET_CC = None
  CC = None
  CFLAGS_arm-linux-androideabi = None
  CFLAGS_arm_linux_androideabi = None
  TARGET_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  running: "arm-linux-androideabi-clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "--target=arm-linux-androideabi" "-Wall" "-Wextra" "-E" "src/android-api.c"
  
  --- stderr
  
  
  error occurred: Failed to find tool. Is `arm-linux-androideabi-clang` installed?
  
  
  
  warning: build failed, waiting for other jobs to finish...
  error: build failed
  ninja: build stopped: subcommand failed.
`

**Comment by alexcrichton** [comment]
Would you be able to use [build script overrides](https://doc.rust-lang.org/cargo/reference/build-scripts.html#overriding-build-scripts) in your use case perhaps?

**Comment by awakecoding** [comment]
@alexcrichton unless I didn't understand build script overrides correctly, my understanding is that it uses a .cargo/config file with fixed paths to specific library locations per target, and therefore lacks the flexibility of the build.rs script. The build.rs script is executed and outputs "cargo:" lines to stdout which is then used by cargo to know how to link to libraries correctly.

My prebuilt libraries are not in easily predictable paths. Instead, I can automatically generate information about where my prebuilt artifacts are. Here is an example from conan-rs that automatically outputs the build information parsed from conan to the format expected in a build.rs script: https://github.com/Devolutions/conan-rs/blob/master/src/lib.rs#L259

If you have a way to override a crate's build.rs script such that I can run mine instead, I would be very interested. In order to be able to use a static .cargo/config file, I would need to run a tool to generate this config file before running the build, which is not very practical.

**Comment by awakecoding** [comment]
OR if there exists a way in cargo to try and apply patches on top of the clean, untouched crates.io latest published sources, this would definitely solve my issue of having to update my branch every time a new version of the patched crate is updated. In other words, if I can supply .patch files, or make cargo extract a path from the diff of two commits and try to apply it on top of the latest sources, it might be possible to automatically patch newer versions, as long as the patch can still be applied.

**Comment by alexcrichton** [comment]
I think unfortunately there may not be a great solution for you in that case? This crate needs the `cc` crate to compiled C code, and if static configuration doesn't work there's unfortunately not much other recourse with Cargo.

**Comment by alexcrichton** [comment]
I'm going to close this because unfortunately this won't work with the organization of the crate today. I hope to switch to gimli-symbolize in the near-ish future which will remove the default dependency on C code.
