### ISSUE TITLE
backtrack-sys CC dependence on parts of target name

### ISSUE THREAD

**Issue by ubamrein** [rust-lang/backtrace-rs#278]
When building for mac catalyst (which is available in the rust master branch as of some time) I faced the problem that backtrack-sys' CC configuration was either trying to build for the iPhone Simulator or for MacOSX but not for the new Macabi (based on if there is ios or darwin in the target name). I'm not familiar with the CC crate, but in the target configuration for Xargo there is a field called "llvm-target", which essential is the target needed to set for the CC.

To circumvent the problem I could, in the end, just apply the CFLAGS="-target x86_64-apple-ios13.0-macabi" to the `xargo build`-command (where the target is as mentioned above the llvm-target specifier for the custom target configuration for Xargo), which overrides the old compiler flags and uses the correct target. I though get warnings since  the previous compiler flags are ignored (related to ios e.g.)

Cheers
Patrick

**Comment by alexcrichton** [comment]
Thanks for the report! This crate though doesn't deal much in terms of flags to C compilers, that's the job of local configuration (as you've found) or the `cc` crate. If you'd like to see this fixed, mind opening an issue on the `cc` crate?

**Comment by ubamrein** [comment]
I will open an issue on the `cc` crate. Thanks!
