### ISSUE TITLE
Build fails on `stable-x86_64-pc-windows-msvc`

### ISSUE THREAD

**Issue by jmcph4** [rust-lang/backtrace-rs#279]
# System Information #
OS: Windows 10 Home (v1903) (18362.592)
`rustup`: rustup 1.21.1 (7832b2ebe 2019-12-20)
Toolchain: stable-x86_64-pc-windows-msvc
`rustc`: rustc 1.40.0 (73528e339 2019-12-16)
`cargo`: cargo 1.40.0 (bc8e4c8be 2019-11-22)

# Actual Behaviour #
When attempting to install [cargo-generate](https://github.com/ashleygwilliams/cargo-generate) on `stable-x86_64-pc-windows-msvc`:

    $ cargo install cargo-generate
    ...
       Compiling backtrace v0.3.42
    error[E0658]: use of unstable library feature 'ptr_cast'
       --> C:\Users\jmcph4\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.42\src\backtrace\dbghelp.rs:110:74
        |
    110 |                 RtlLookupFunctionEntry(addr, &mut base, ptr::null_mut()).cast()
        |                                                                          ^^^^
        |
        = note: for more information, see https://github.com/rust-lang/rust/issues/60602
    
    error: aborting due to previous error
    
    For more information about this error, try `rustc --explain E0658`.
    error: Could not compile `backtrace`.

# Expected Behaviour #
The crate should build correctly on the target platform.

**Comment by philipc** [comment]
Are you sure you are using rustc 1.40? I think `cast` was stabilised in 1.38. I tried with rustc 1.39 and it worked for me.

**Comment by jmcph4** [comment]
I just tested on my Windows 7 machine with the same environment (apart from the OS obviously) and it works fine.

I have also attempted the install of `cargo-generate` multiple times on the original Windows 10 machine - to no avail.

**Comment by alexcrichton** [comment]
Hm yes today's stable should work. If it doesn't though I'll have to wait until I get home to a Windows computer to verify.

**Comment by jmcph4** [comment]
I just attempted to install `cargo-generate` again and it worked. Unless there's a particular PR or commit that should be referenced, this can probably be closed as fixed.

**Comment by alexcrichton** [comment]
Ok!
