### ISSUE TITLE
Build error: expected an item keyword @ backtrace\dbghelp.rs:119:13

### ISSUE THREAD

**Issue by leocavalcante** [rust-lang/backtrace-rs#280]
I'm not being able to build my project after adding the [mysql](https://docs.rs/mysql/17.0.0/mysql/) crate as dependency.

```
error: expected an item keyword
   --> C:\Users\info\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.42\src\backtrace\dbghelp.rs:119:13
    |
119 |             let function_table_access = dbghelp.SymFunctionTableAccess64();
    |             ^^^
```

Not sure where I should submit the issue, because [backtrace doesn't seams to be a direct dependency of it](https://github.com/blackbeam/rust-mysql-simple/blob/master/Cargo.toml) neither.

Also, it seams that the code pointed in the error was introduced @ 0.3.42 by https://github.com/rust-lang/backtrace-rs/pull/274

**Comment by alexcrichton** [comment]
Thanks for the report, I've published 0.3.43 which I think should fix the issue.
