### ISSUE TITLE
Can we yank version 0.3.42?

### ISSUE THREAD

**Issue by jebrosen** [rust-lang/backtrace-rs#285]
backtrace 0.3.43 was released with a fix for the `cfg-if` dependency version. Since it was the only change, can 0.3.42 be yanked? This is causing problems when combined with projects that set a `cfg-if = 0.1.9` to preserve a lower MSRV, e.g. https://github.com/SergioBenitez/Rocket/pull/1204#issuecomment-583876032

**Comment by alexcrichton** [comment]
Sure thing, done!
