### ISSUE TITLE
Get register values for frame

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/backtrace-rs#288]
I got a PR for https://github.com/bjorn3/pretty_backtrace which shows the values of locals for every frame.This currently requires `unwind-rs` to get the register values. Unfortunately it only supports ELF based unixes. Adding support to `backtrace-rs` would make it possible to do it on macOS too.

When using libunwind, this can use `_Unwind_GetGR`. On Windows, you can get register values from `CONTEXT`.

**Comment by alexcrichton** [comment]
Seems reasonable to me to add!

**Comment by bjorn3** [comment]
Looking at the libgcc source code I'm not sure this can safely be added:

https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=libgcc/unwind-dw2.c;h=d0afce7a9ea9f5b12a5a01ef1e940e1452b48cab;hb=HEAD#l247

> ```c
>   /* This will segfault if the register hasn't been saved. */
> ```

**Comment by workingjubilee** [comment]
Hmm.

Alright, then we can probably close this for now.
