### ISSUE TITLE
Compile libbacktrace with mmapio.c instead of read.c

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/backtrace-rs#289]
Currently, `backtrace-sys` hardcoded the compilation of `src/libbacktrace/read.c`: https://github.com/rust-lang/backtrace-rs/blob/190b2f9bb1df384be686eadd1d14cb95de0d87d4/crates/backtrace-sys/build.rs#L33

However, `libbacktrace` [provides a more efficient version of `read.c`](https://github.com/ianlancetaylor/libbacktrace/issues/32#issuecomment-586131352) (which is used internally to read in chunks of memory) called `mmapio.c`.

`backtrace-rs` should either provide a feature which compiles `libbacktrace` with `mmapio.c`, or attempt to detect whether or not the `mmap` system call is available. Alternatively, the `configure` script for `libbacktrace` could be used instead of hard-coding paths, since [it already detects if `mmap` is available[(https://github.com/ianlancetaylor/libbacktrace/blob/559ab7cab4a6002124863d493bd09a376a690e76/configure.ac#L285-L303). I'm not sure if there are any issues preventing this script from being used.

This will also fix https://github.com/rust-lang/rust/issues/69151, since we will no longe be hitting the bug in `read.c`

**Comment by alexcrichton** [comment]
A PR to implement this would be most welcome! I don't think anything fancy needs to be done, `mmap` is available everywhere reasonable.
