### ISSUE TITLE
Cross compilation always picks up host architecture.

### ISSUE THREAD

**Issue by amrx101** [rust-lang/backtrace-rs#292]
I have a small procject that has `backtrace-rs` as a dependency. I am trying to cross-compile the project for `armv7-unknown-linux-gnueabihf`.

The contents of my .cargo file

      [target.armv7-unknown-linux-gnueabihf]
      linker = arm-linux-gnueabihf-gcc --sysroot=/test/fds/filesystem/rootfs -march=armv7-a -marm -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a9 $@

But the cross compilation for `backtrace-sys` fails.

The stderr 

        process didn't exit successfully: `<path_to_project>target/release/build/backtrace-sys-b663c31ae0dd7e60/build-script-build` (exit code: 1)
       --- stdout
       cargo:rustc-cfg=rbt
      TARGET = Some("x86_64-unknown-linux-gnu")
       OPT_LEVEL = Some("3")
      HOST = Some("x86_64-unknown-linux-gnu")
      CC_x86_64-unknown-linux-gnu = None
      CC_x86_64_unknown_linux_gnu = None
      HOST_CC = None
      CC = Some("arm-linux-gnueabihf-gcc")
      CFLAGS_x86_64-unknown-linux-gnu = None
      CFLAGS_x86_64_unknown_linux_gnu = None
       HOST_CFLAGS = None
      CFLAGS = None
      CRATE_CC_NO_DEFAULTS = None
      CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")

      cargo:warning=arm-linux-gnueabihf-gcc: error: unrecognized command line option ‘-m64’

The target mentioned here is not the target that I specify in my .cargo. 

What am I missing here? 
Thanks

**Comment by alexcrichton** [comment]
Thanks for the report, but this is a bug report for the `cc` project which is used to select compiler and doesn't read Cargo's toml configuration.
