### ISSUE TITLE
Make a new point release

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/backtrace-rs#301]
It would be nice to have a release that includes https://github.com/rust-lang/backtrace-rs/pull/298 and https://github.com/rust-lang/backtrace-rs/pull/297, which fix issues in `libstd` and `miri` respectively.

**Comment by Amanieu** [comment]
A new version was just released 1 hour ago. We're just missing an update to `Cargo.lock` in rust-lang/rust.

**Comment by Aaron1011** [comment]
I checked this repository earlier today, and didn't check again before making this issue :laughing:
