### ISSUE TITLE
 Define HAVE_KERN_PROC on FreeBSD to fix rust-lang/rust#54434 (#294) 

### ISSUE THREAD

**Issue by przygienda** [rust-lang/backtrace-rs#304]
Define HAVE_KERN_PROC on FreeBSD to fix rust-lang/rust#54434 (#294) 

that precisly broke my FreeBSD 11 build here 

clang version 5.0.2  (based on LLVM 5.0.2)
Target: amd64-unknown-freebsd11.0
Thread model: posix

[backtrace-sys 0.1.35] cargo:warning=src/libbacktrace/fileline.c:113:45: error: use of undeclared identifier 'KERN_PROC'
[backtrace-sys 0.1.35] cargo:warning=  return sysctl_exec_name (state, CTL_KERN, KERN_PROC, KERN_PROC_PATHNAME, -1,
[backtrace-sys 0.1.35] cargo:warning=                                            ^
[backtrace-sys 0.1.35] cargo:warning=src/libbacktrace/fileline.c:113:56: error: use of undeclared identifier 'KERN_PROC_PATHNAME'
[backtrace-sys 0.1.35] cargo:warning=  return sysctl_exec_name (state, CTL_KERN, KERN_PROC, KERN_PROC_PATHNAME, -1,
[backtrace-sys 0.1.35] cargo:warning=                                                       ^
[backtrace-sys 0.1.35] cargo:warning=2 errors generated.

**Comment by przygienda** [comment]
0.1.32 was compiling and working fine

**Comment by alexcrichton** [comment]
cc @t6, can you help taking a look at this?

**Comment by t6** [comment]
> clang version 5.0.2 (based on LLVM 5.0.2)
> Target: amd64-unknown-freebsd11.0

That's a very old Clang version. What FreeBSD version are you on?

FreeBSD < 11.3 does not have KERN_PROC and is also not supported anymore since last year.

**Comment by przygienda** [comment]
sigh, ok, yeah, I'm on old FreeBSD 11.0 ...

**Comment by przygienda** [comment]
FreeBSD 11.0 is 3 years old only. It's pretty frightening if such a base package is obsoleting that fast frankly. I'm relying on that in long chains of dependencies and things like GNU/C or C++ drag stuff for 20 years ...

**Comment by przygienda** [comment]
any way you gentlemen can add a feature for BSD 11? I'm not sure how to recursively force all packages to compile libbacktrace with such a feature but I can't move up from BSD 11 so it basically completely broke my code since stuff is being pulled in by sysctl which I don't want to factor out ...

**Comment by cemeyer** [comment]
In March 2020, 11.0 was three years and five months old, 11.1 was two years and eight months old, 11.2 was a year and eight months old, and 11.3 was eight months old.

Can we close this issue?

**Comment by alexcrichton** [comment]
Indeed!
