### ISSUE TITLE
Failed to run custom build command

### ISSUE THREAD

**Issue by MagixInTheAir** [rust-lang/backtrace-rs#307]
Hello everyone,

Here is my [full compilation error](https://pastebin.com/mVPHm2jt). 
It stops me from using a dependant crate. 

My system is Windows 10, fully updated. Installed rust through Chocolatey.

Thanks

**Comment by philipc** [comment]
The error message you are getting is:

> running: "gcc.exe"  [...] sorry, unimplemented: 64-bit mode not compiled in

You need to install a 64-bit gcc. See https://github.com/alexcrichton/cc-rs#compile-time-requirements
