### ISSUE TITLE
Add an alloc feature

### ISSUE THREAD

**Issue by fintelia** [rust-lang/backtrace-rs#308]
If there was an _alloc_ feature in addition to the _std_ feature then parts of the library that need allocation but not the rest of the standard library could still be used in a no_std context. 

This would unblock https://github.com/rust-lang/rust/issues/62502, which in turn would unblock https://github.com/rust-lang/rust/issues/48331.

**Comment by alexcrichton** [comment]
I would be ok reorganizing things, but I would prefer that the decision that the libs team wants to solve rust-lang/rust#48331 be made first before the effort to reorganize things is put in.

**Comment by fintelia** [comment]
That seems reasonable. Is there something that needs to be done to get that on the libs team agenda? The discussion on that other issue seems to have stalled.

**Comment by Amanieu** [comment]
Note that this won't really solve the issue since `backtrace` depends on `libc`, which we really don't want as a dependency of `alloc`.

**Comment by alexcrichton** [comment]
I'm going to close this because I don't think this needs to be done at this time, and integration into libstd is a very tricky problem beyond simply shuffling imports.
