### ISSUE TITLE
[question] Global lock in backtrace

### ISSUE THREAD

**Issue by idubrov** [rust-lang/backtrace-rs#309]
What is the purpose of taking a global lock [here](https://github.com/rust-lang/backtrace-rs/blob/e8404c8aae6c826c74033f2961821d854898b4f9/src/backtrace/mod.rs#L52) when collecting backtraces?

Why locking is necessary when backtraces are only collected (but not resolved)?

Pardon my ignorance, but I didn't find any explanation.

We are seeing issues in production code that are related to that lock (still figuring out how exactly are we getting something that looks like a deadlock), and I'm curious why is it necessary for collecting traces?

**Comment by SirJohnFalstaff** [comment]
Looks like it is required for `dbghelp` API. Why is it applied on other platforms as well?

**Comment by alexcrichton** [comment]
Yeah as found this is required for correctness on Windows. Other platforms also currently make assumptions based on this, including gimli/libbacktrace/etc. It's not fundamentally required for some techniques so some refactorings could be used to avoid it, but it would likely be quite difficult. 

Do you have mor einfo on deadlocks/etc which I might be able to help out with?

**Comment by idubrov** [comment]
It turned out to be a very slow first initialization of libbacktrace (up to 180 seconds in kubernetes environment!) which caused all the threads that only try to create a new `Backtrace` instance to be blocked.

So, it was a combination of these factors:

1. Our binary is pretty big (~1.5 Gb with debug symbols).
2. Our kubernetes environment has serious variability: the first backtrace initialization happens in the range of 1.5 seconds to 180 seconds (across multiple pods / containers)!
3. We had a code path which would create an error, convert it to `failure::Error` (which causes backtrace to be initialized), then checked with `.is_err()` and ignored. It made this part of the code to be affected by the lock.

So, when we tried to print backtrace for the first time, it would block all threads trying to just capture backtraces, for up to 180 seconds.

We upgraded to `0.3.46` and switched on `gimli-symbolize` (based on [this](https://github.com/rust-lang/backtrace-rs/issues/222#issuecomment-509244071) comment) to see if that helps to reduce these delays. So far it does seem to be doing better, but still could be ~7 seconds the first time backtrace is formatted / printed.

**Comment by idubrov** [comment]
Not sure if anything could be done here (outside of some more efficient initialization?).

I was thinking that if trace wouldn't be using lock, we wouldn't have that issue. However, it would affect us less only because we create backtraces, but never print them (which is the part of the code we need to fix anyways). Normally, I would expect that if code captures backtrace it will actually eventually format it, at which point lock would be needed (with current implementations).

**Comment by alexcrichton** [comment]
Ah ok makes sense! FWIW do you know if you're using `Backtrace::new` or `Backtrace::new_unresolved`? In theory the latter is much faster if it's never printed, since it delays parsing debuginfo until the backtrace is actually resolved and symbolized. Depending on your use case it may help make startup much speedier.

**Comment by idubrov** [comment]
This part was using conversion into `failure::Error`, which seems to be using `new_unresolved`: https://github.com/rust-lang-nursery/failure/blob/e7817e4044449c2b57ff8babca42b7b72eb2d99d/src/backtrace/internal.rs#L46

I think, the issue was because of this lock -- `new_unresolved` still grabs the lock, so it will wait on it if other thread is doing an expensive resolution (the initial one, for example, that initializes the whole `libbacktrace`)..

**Comment by alexcrichton** [comment]
Bummer! Would it be possible for me to poke around with this executable? I'd be curious to see a profiling of where time is being spent.

In general removing the lock probably won't help here. If there's not global state it'd be per-thread, and that just means each thread would do all the work the main thread is doing. The best fix here is to probably optimize the actual runtime itself, either by delaying work or something like that.

**Comment by idubrov** [comment]
It's some proprietary code we have so I cannot share it, unfortunately.

I was kind of thinking that if capturing backtrace wouldn't require lock, it would at least not block those who only capture backtraces (but never "resolve" them). My thinking-from-first-principles was that if code is capturing their own stack, it shouldn't need to synchronize with other threads and shouldn't have any need for shared state.

**Comment by alexcrichton** [comment]
Ah no worries. FWIW I'm not trying to disagree with you that the lock may not be always necessary. I'm mostly saying that it would be a pretty significant chunk of work to remove it, which I don't personally at least have time for right now.

If there's an easy way to optimize this via a different route I think that would likely bear fruit much more quickly. If you're able to get a profile of where time is being spent, that'd be quite useful for figuring out how to debug this.

**Comment by idubrov** [comment]
Thank you for you help! I wasn't really implying any extra work for you; was just trying to explain my thinking that resulted in the question I asked in this issue.

I think, I got my answers, so I'm going to close this. We might attempt profiling at some point; I'll report if we get anything interesting.
