### ISSUE TITLE
Frequent crashes on macOS

### ISSUE THREAD

**Issue by jdm** [rust-lang/backtrace-rs#312]
Per https://github.com/rust-lang/rust/issues/71397#issuecomment-617346994, the latest update to backtrace-rs now frequently causes segfaults on macOS.

**Comment by jdm** [comment]
The issue reproduces easily when using RUST_BACKTRACE=1 and the sample program in https://github.com/rust-lang/rust/issues/71397#issuecomment-617357602. Trying to adapt it to use backtrace-rs directly (`println!("{:?}", backtrace::Backtrace::new())`) is not causing the crash to appear, however.

**Comment by alexcrichton** [comment]
Thanks for the heads up! I've confirmed locally that it looks like this is the same as https://github.com/rust-lang/backtrace-rs/issues/310 which has been [fixed and published](https://github.com/rust-lang/backtrace-rs/issues/310#issuecomment-616758543). To fix the rust-lang/rust bug I believe the dependency just needs an update.
