### ISSUE TITLE
Gimli doesn't support OpenBSD

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/backtrace-rs#326]
I believe all that's necessary to support OpenBSD is to upstream a definition of `dl_iterate_phdr` into the `libc` crate, after that support should be as simple as updating [this line](https://github.com/rust-lang/backtrace-rs/blob/bb5aa64804d6ba83a768c7ed1c5d67435ddba53e/src/symbolize/gimli.rs#L270-L273).

**Comment by workingjubilee** [comment]
libc has support for `dl_iterate_phdr` on all the BSDs I can think of now, and as of https://github.com/rust-lang/backtrace-rs/pull/512 we appear to have support across FreeBSD, NetBSD, and OpenBSD, so I am declaring the main battle won and closing this! If any BSDs need additional work, as I know there are more than just those three, we can pursue them in new issues and PRs. Fortunately, most are based on NetBSD and FreeBSD, with the exception of the one extant BSD that I am aware of which, like those, forks from the original BSD4: "Darwin", better known as macOS.
