### ISSUE TITLE
Symbolication of dynamic libraries doesn't work on MinGW

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/backtrace-rs#333]
The test added in https://github.com/rust-lang/backtrace-rs/pull/332 is failing on MinGW. I believe the cause is [here](https://github.com/rust-lang/backtrace-rs/blob/1ca764ecabcd8db4e7a9c61ef73a7f22a6e779b8/src/symbolize/gimli.rs#L105-L120), which is that we don't actually attempt to load information about native libraries.

**Comment by mati865** [comment]
I suppose this cdylib has dependency on libgcc_s unwind library. Maybe it's not loaded properly?
ASLR is most likely now enabled by default with LD BFD.

**Comment by alexcrichton** [comment]
Fixed in https://github.com/rust-lang/backtrace-rs/pull/345
