### ISSUE TITLE
Use of `object` in 0.3.48 broke support for Rust v1.37

### ISSUE THREAD

**Issue by stevenroose** [rust-lang/backtrace-rs#335]
It seems that this commit https://github.com/rust-lang/backtrace-rs/commit/1ffdc8ae1c254e6a2c22b656f4efd2ecde5c3363 added the object dependency which is not compatible with Rust v1.37.

**Comment by stevenroose** [comment]
Please rollback that change and release 0.3.49 and then release 0.4.0 with this change.

**Comment by alexcrichton** [comment]
Thanks for the report! The policy of this crate is 2 versions back, however, so this isn't something I'm going to fix. If you'd like to send PRs to crates to lower their required version then that should be ok.
