### ISSUE TITLE
Gimli doesn't support Android

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/backtrace-rs#351]
same as https://github.com/rust-lang/backtrace-rs/issues/350, but for Android

**Comment by lzutao** [comment]
Starting from lollipop (android 5, api level 21), android defines `dl_iterate_phdr` in <link.h> [1].
Currently, rustc supports down to api level 14 [2].
I will investigate more about other possibilities but if you have opinions
on this issue, please make a voice.

[1]: https://android.googlesource.com/platform/bionic/+/refs/heads/master/docs/status.md
[2]: https://github.com/rust-lang/rust/blob/ae9731ce1db8afa4794110f1b4780b9128a5cae8/src/ci/docker/host-x86_64/arm-android/Dockerfile#L8

**Comment by alexcrichton** [comment]
It might be possible to use `dlsym` on Android to cover the differences, although another possibility is to look to increase the API level in rust-lang/rust

**Comment by s1341** [comment]
I'm interested in getting backtraces on Android. Currently I get a list of "<unknown>"s....

Is there any working solution?

**Comment by s1341** [comment]
I got it working, trick was to add `default-features = false` and `features = [ "std", "libbacktrace" ]`

**Comment by kjvalencik** [comment]
@s1341 Were there any additional steps you needed to take? Switching to `backtrace-sys` with the `libbacktrace` feature flag was insufficient.

**Comment by s1341** [comment]
@kjvalencik I had to turn off default-features too. It wasn't enough to turn on `libbacktrace`.

**Comment by jrose-signal** [comment]
I'm not 100% sure this is the same issue but I'll note that Signal has encountered some Android devices that claim to be API22 but still don't have `dl_iterate_phdr`. A `dlsym`-based solution would be safest for us.

**Comment by kjvalencik** [comment]
@jrose-signal That would impact both the `backend-sys` implementation as well as https://github.com/rust-lang/backtrace-rs/pull/415 which both depend on the API version being targeted at compile time to determine if `dl_iterate_phdr` is available.

Are you able to provide any additional details or link to an issue? Thanks!

**Comment by jrose-signal** [comment]
Ah, I take it back: upon further investigation we've had some builds come out that are missing `-ldl`. I'm not sure how they even linked, honestly. Still looking to see if this is the only issue.

**Comment by jrose-signal** [comment]
For anyone curious: I never quite tracked it down, but our Docker build was not including `-ldl` even though our other builds were, and this only caused problems on *some* phones because most of them re-export the libdl APIs through libc (or something else that meant it didn't need to be explicitly linked). signalapp/libsignal-client#274
