### ISSUE TITLE
target `mipsel-unknown-linux-uclibc` cant compile with 0.3.49

### ISSUE THREAD

**Issue by kolapapa** [rust-lang/backtrace-rs#355]
![image](https://user-images.githubusercontent.com/17918689/86124721-27ce7700-bb0e-11ea-8233-d7f741275798.png)

target `mipsel-unknown-linux-uclibc` compile with `backtrace`(0.3.49) with error message.

but with `backtrace`(0.3.46) is success.

seems to be `libc` library not defined.

**Comment by alexcrichton** [comment]
Thanks for the report, but it looks like this isn't a bug in the `backtrace` crate but rather a missing binding from the `libc` crate. The uclibc target doesn't have `dl_iterate_phdr` defined, but it looks like it should be relatively easy to add to the `libc`crate!
