### ISSUE TITLE
Instruction pointer address: absolute or relative?

### ISSUE THREAD

**Issue by dmitry-zakablukov** [rust-lang/backtrace-rs#366]
Good day!

What kind of address `Frame::ip()` returns: absolute or relative to the image base address?
If the address is absolute, then the image base address is required to decode backtrace using a PDB file (on Windows). But I see no public methods to get the image base address.

**Comment by alexcrichton** [comment]
Addresses returned are currently always absolute in the process address space. This would be good to add to the documentation!

**Comment by dmitry-zakablukov** [comment]
@alexcrichton , is there way to get the image base address from the backtrace crate?

**Comment by alexcrichton** [comment]
There is not, no.

**Comment by dmitry-zakablukov** [comment]
@alexcrichton , then how about to extend the `Frame` trait as follows?
```
impl Frame {
    ...
    
    /// Returns the base address of the module to which a frame belongs.
    pub fn module_base_address(&self) -> Option<*mut c_void>;
    
    /// Returns the name of the module to which a frame belongs.
    pub fn module_name(&self) -> Option<String>;
}
```

These functions return an option, because some Frame implementations may not be able to provide such an information. But I know for sure that dbghelp can provide module base address at least.

The proposed api will allow to decode a backtrace on Windows when the PDB file with a debug info is missing.

**Comment by alexcrichton** [comment]
Seems plausible to me to add!

**Comment by dmitry-zakablukov** [comment]
Ok, then I'll try to make a pr to achieve this.

**Comment by dmitry-zakablukov** [comment]
PR is opened: #368 
`module_name()` method is not implemented, because the crate doesn't use `String` and, in my opinion, base address of the module should be sufficient to get module name in a caller.

**Comment by dmitry-zakablukov** [comment]
PR was merged, so I close the issue.

**Comment by jyn514** [comment]
FWIW, you could implement `module_name` like so:
```rust
                let mut info = libc::Dl_info {
                    dli_fname: null(),
                    dli_fbase: null_mut(),
                    dli_sname: null(),
                    dli_saddr: null_mut(),
                };
                let status = unsafe { libc::dladdr(addr, &mut info) };
                if status != 0 && !info.dli_fname.is_null() {
                    let fname = unsafe { CStr::from_ptr(info.dli_fname) };
                }
```
