### ISSUE TITLE
Implement filtering behaviour like RUST_BACKTRACE=short

### ISSUE THREAD

**Issue by jdm** [rust-lang/backtrace-rs#38]
https://github.com/rust-lang/rust/pull/38165 looks really nice for default backtrace behaviour for panics. We should make it easy to obtain similar output from this library, too!

**Comment by fitzgen** [comment]
cc @Yamakaky

**Comment by Yamakaky** [comment]
I was thinking maybe we could stabilize a `std::sys::backtrace` module (name to be discussed). That way it would be easier for third-party tools to use the exact same code. Another solution would be to move the compiler code to a new crate just for backtrace handling.

See also https://github.com/rust-lang/rust/pull/40264.

**Comment by alexcrichton** [comment]
Sounds reasonable to me!

I don't think we should stabilize a module in `std`

**Comment by alexcrichton** [comment]
Implemented in https://github.com/rust-lang/backtrace-rs/pull/245
