### ISSUE TITLE
failed to run custom build command

### ISSUE THREAD

**Issue by errrken** [rust-lang/backtrace-rs#408]
Hi there,

On Apple Silicon, running a rust docker image (native) to cross compile for x86_64-unknown-linux-musl, I get below:

#10 30.66 error: failed to run custom build command for `backtrace-sys v0.1.37`
#10 30.66 
#10 30.66 Caused by:
#10 30.66   process didn't exit successfully: `/app/target/release/build/backtrace-sys-152f7f148796c1f9/build-script-build` (exit code: 1)
#10 30.66   --- stdout
#10 30.66   cargo:rustc-cfg=rbt
#10 30.66   TARGET = Some("x86_64-unknown-linux-musl")
#10 30.66   OPT_LEVEL = Some("3")
#10 30.66   HOST = Some("aarch64-unknown-linux-gnu")
#10 30.66   CC_x86_64-unknown-linux-musl = None
#10 30.66   CC_x86_64_unknown_linux_musl = None
#10 30.66   TARGET_CC = None
#10 30.66   CC = None
#10 30.66   CROSS_COMPILE = None
#10 30.66   CFLAGS_x86_64-unknown-linux-musl = None
#10 30.66   CFLAGS_x86_64_unknown_linux_musl = None
#10 30.66   TARGET_CFLAGS = None
#10 30.66   CFLAGS = None
#10 30.66   CRATE_CC_NO_DEFAULTS = None
#10 30.66   DEBUG = Some("false")
#10 30.66   CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
#10 30.66   running: "musl-gcc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "src/libbacktrace" "-I" "/app/target/x86_64-unknown-linux-musl/release/build/backtrace-sys-5dc34719010992d0/out" "-fvisibility=hidden" "-DBACKTRACE_ELF_SIZE=64" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-Dmacho_get_view=__rbt_macho_get_view" "-Dmacho_symbol_type_relevant=__rbt_macho_symbol_type_relevant" "-Dmacho_get_commands=__rbt_macho_get_commands" "-Dmacho_try_dsym=__rbt_macho_try_dsym" "-Dmacho_try_dwarf=__rbt_macho_try_dwarf" "-Dmacho_get_addr_range=__rbt_macho_get_addr_range" "-Dmacho_get_uuid=__rbt_macho_get_uuid" "-Dmacho_add=__rbt_macho_add" "-Dmacho_add_symtab=__rbt_macho_add_symtab" "-Dmacho_file_to_host_u64=__rbt_macho_file_to_host_u64" "-Dmacho_file_to_host_u32=__rbt_macho_file_to_host_u32" "-Dmacho_file_to_host_u16=__rbt_macho_file_to_host_u16" "-o" "/app/target/x86_64-unknown-linux-musl/release/build/backtrace-sys-5dc34719010992d0/out/src/libbacktrace/alloc.o" "-c" "src/libbacktrace/alloc.c"
#10 30.66   cargo:warning=cc1: error: unrecognized command line option '-m64'
#10 30.66   exit code: 1

Any ideas?

Thanks

**Comment by alexcrichton** [comment]
Thanks for the report, but this looks like a misconfigured native compiler where `musl-gcc` doesn't recognize `-m64`. That looks like your local musl compiler may not be configured or set up correctly.
