### ISSUE TITLE
release 0.3.57

### ISSUE THREAD

**Issue by jclulow** [rust-lang/backtrace-rs#418]
Hi!

Would it be possible to get a 0.3.57 release so that I can go and bump the version used in the Rust toolchain so that we can get illumos support there?  I wasn't sure if you had a process for creating the version bump and doing the tag/publish, etc -- but if I should file a `Cargo.toml` PR please let me know!

Thank you.

**Comment by alexcrichton** [comment]
Sure thing, published!
