### ISSUE TITLE
frames cannot be resolved on macOS

### ISSUE THREAD

**Issue by winterqt** [rust-lang/backtrace-rs#443]
### code
```rust
fn main() {
    backtrace::trace(|frame| {
        println!("frame: {:?}", frame);

        // Resolve this instruction pointer to a symbol name
        backtrace::resolve_frame(frame, |symbol| {
            println!("\tname: {:?}", symbol.name());
            println!("\tfilename: {:?}", symbol.filename());
        });

        true // keep going to the next frame
    });
}
```

### output
```
frame: Frame { ip: 0x1046c2048, symbol_address: 0x1046c2048 }
frame: Frame { ip: 0x1046c2098, symbol_address: 0x1046c2098 }
frame: Frame { ip: 0x1046c1e18, symbol_address: 0x1046c1e18 }
frame: Frame { ip: 0x1046c1a40, symbol_address: 0x1046c1a40 }
frame: Frame { ip: 0x1046c1d98, symbol_address: 0x1046c1d98 }
frame: Frame { ip: 0x1046c1c14, symbol_address: 0x1046c1c14 }
frame: Frame { ip: 0x104780c14, symbol_address: 0x104780c14 }
frame: Frame { ip: 0x1046c1bdc, symbol_address: 0x1046c1bdc }
frame: Frame { ip: 0x1046c1e40, symbol_address: 0x1046c1e40 }
```

### rustc version info
```
rustc 1.55.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: aarch64-apple-darwin
release: 1.55.0
LLVM version: 12.0.1
```

`backtrace` version: 0.3.61

I can also reproduce this with `std::backtrace` on the nightly from `2021-10-13`, but I think this is the most fitting place to file this issue (let me know if it isn't, and I'll open an issue in the Rust repo).

**Comment by winterqt** [comment]
Ah, fun.

I'd be willing to help figure this out. Where should I start looking in the codebase, what handles the system libraries / debuginfo?

**Comment by alexcrichton** [comment]
Oh there may also be bits in this file as well to debug -- https://github.com/rust-lang/backtrace-rs/blob/master/src/symbolize/gimli/macho.rs

**Comment by alexcrichton** [comment]
For the last line I get that myself locally as well, and I think it's the inability to trace throuh some system libraries perhaps? I think it's definitely indicative of a bug in any case in this library somewhere because I don't believe it has anything to do with the filename/line number reported.
