### ISSUE TITLE
Make `gimli` / `addr2line` optional on windows

### ISSUE THREAD

**Issue by Jasper-Bekkers** [rust-lang/backtrace-rs#451]
Right now `gimli` is always compiled in it looks like. However, since it only targets DWARF, I think it could be an optional feature on windows.

On our windows builds we seem to be spending a good ~15 seconds building `gimli` (since addr2line needs it) without actually every needing or using it.

**Comment by workingjubilee** [comment]
If a PR is submitted adding the appropriate cfg and diligently modularizing the relevant code, we will likely accept it.

**Comment by klensy** [comment]
Should be fixed by #543
