### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by lattice0** [rust-lang/backtrace-rs#475]
We do valgrind checks on this repo and we're getting this: https://github.com/fzyzcjy/flutter_rust_bridge/pull/582#issuecomment-1207237333

which only happens when we use this backtrace lib. Is it possible that this lib has a memory leak? Has it ever been tested with valgrind?

Thank you very much!

**Comment by bjorn3** [comment]
I believe valgrind gives false positives on statx calls.

**Comment by workingjubilee** [comment]
Closing for the same reasons https://github.com/rust-lang/rust/issues/68979 was closed, this is kinda-sorta a Valgrind bug.
