### ISSUE TITLE
tests/concurrent-panics.rs doesn't have a #[test]

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/backtrace-rs#487]
tests/concurrent-panics.rs doesn't have a #[test], which AFAICT means it won't get run when you do `cargo test`.

I encountered this because I started working on another unit test for a different problem, and was modelling my test after what concurrent-panics.rs says.  Then I eventually realized that the reason my unit test was always passing was because it was never getting run by `cargo test`.

Should we add a `#[test]` to the [`fn main` in test/concurrent-panics.rs](https://github.com/rust-lang/backtrace-rs/blob/8b83ba10fc8ccfc12ff75fcc3277286c0b9fad62/tests/concurrent-panics.rs#L12)? 

https://github.com/rust-lang/backtrace-rs/blob/8b83ba10fc8ccfc12ff75fcc3277286c0b9fad62/tests/concurrent-panics.rs#L10-L14

**Comment by pnkfelix** [comment]
(this is a little tricky to resolve, since depending on how the file is compiled, the recursive invocation may be of the **test driver**, not just the file as a standalone entity. But I bet there's a way to architect it so that you get the desired effect in either context... I'll give it some thought...)

**Comment by bjorn3** [comment]
This test uses `harness = false`, so it is compiped as executable withou lt the libtest driver for `#[test]`: https://github.com/rust-lang/backtrace-rs/blob/8b83ba10fc8ccfc12ff75fcc3277286c0b9fad62/Cargo.toml#L129-L132

**Comment by pnkfelix** [comment]
Ah!

That's embarrassing, I should have dug deeper (either by deliberately breaking the test locally to test the test, or by looking at https://github.com/rust-lang/backtrace-rs/commit/779bca88244cfd649acf1209e396a6ee4cd3febf more carefully, which has the configuration in the `Cargo.toml` that you described) before filing this issue.

thanks @bjorn3 !
