### ISSUE TITLE
Android CI is broken

### ISSUE THREAD

**Issue by Amanieu** [rust-lang/backtrace-rs#531]
This seems to be related to https://github.com/rust-lang/rust/issues/103673. Essentially we need to update the CI scripts to use a newer NDK version. Possible inspiration can be taken from the rust-libc CI scripts, which are similar to the ones in this crate.

**Comment by workingjubilee** [comment]
cc aarch64 android maintainers: @chriswailes @maurer @mgeisler

Hello! Our backtrace crate is deep in arrears on maintenance and we could use all the help we can get. It should be a relatively simple fix, tho'.

**Comment by Good1103** [comment]
Don't merge

**Comment by chriswailes** [comment]
I'd be happy to take a look at this tomorrow.

**Comment by chriswailes** [comment]
Sorry for the delay.  It looks like https://github.com/rust-lang/backtrace-rs/pull/534 will bring the CI definition up to date.

**Comment by workingjubilee** [comment]
Completely fine! It's great to have this taken care of!
