### ISSUE TITLE
MSRV regression on Windows

### ISSUE THREAD

**Issue by camshaft** [rust-lang/backtrace-rs#597]
We run rustc 1.71.1 in our CI and noticed that the Windows builds started failing yesterday: https://github.com/aws/s2n-quic/actions/runs/8394213178/job/22990857677?pr=2159#step:8:390.

The newest release seems to be using `ptr::from_ref`, which was not stabilized [until 1.76.0](https://doc.rust-lang.org/std/ptr/fn.from_ref.html). However, the documented MSRV in the backtrace crate is 1.65.0: https://github.com/rust-lang/backtrace-rs/blob/6fa4b85b9962c3e1be8c2e5cc605cd078134152b/Cargo.toml#L18

Either we should use something that is compatible with 1.65 or the MSRV needs to be bumped. 

I also noticed that the CI does not test against your advertised MSRV: https://github.com/rust-lang/backtrace-rs/blob/6fa4b85b9962c3e1be8c2e5cc605cd078134152b/.github/workflows/main.yml#L19-L36 This should also be addressed :).

**Comment by ChrisDenton** [comment]
See https://github.com/rust-lang/backtrace-rs?tab=readme-ov-file#supported-rust-versions

By that policy the current MSRV is actually 1.75 (or maybe 1.74 since the latest release is still new), it just hasn't been updated elsewhere yet. MSRV is tested but currently only for Linux: https://github.com/rust-lang/backtrace-rs/blob/6fa4b85b9962c3e1be8c2e5cc605cd078134152b/.github/workflows/main.yml#L235-L244

**Comment by workingjubilee** [comment]
Ah, my apologies. Yes, we need to run the MSRV tests on Windows too, I suppose, but yes, any replacement is allowed to be one that breaks your CI anyways.

**Comment by camshaft** [comment]
> By that policy the current MSRV is actually 1.75 (or maybe 1.74 since the latest release is still new), it just hasn't been updated elsewhere yet.

I guess that's fine. It just makes it more difficult to debug when consuming without having the `rust-version` updated in Cargo.toml.

**Comment by workingjubilee** [comment]
I'll try to get a 0.3.71 out the door, it looks like `ptr::from_ref` was the only breaking thing there, and get 0.3.70 yanked, after https://github.com/rust-lang/backtrace-rs/pull/598

**Comment by workingjubilee** [comment]
0.3.71 is published and 0.3.70 is yanked!

**Comment by camshaft** [comment]
Thanks!
