### ISSUE TITLE
'assertion failed: sym - actual_fn_pointer < 1024'

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-lang/backtrace-rs#83]
```
	thread 'smoke_test_frames' panicked at 'assertion failed: sym - actual_fn_pointer < 1024', tests/smoke.rs:74:12
```

Not sure how to debug it, I'm running Fedora 28 x86_64 with rustc 1.22.1 and cargo 0.23.0.

**Comment by alexcrichton** [comment]
I'm going to close this to clean up the issue tracker here. If the test is still failing it probably needs a code change to get it running here, but I don't want to track getting the test suite running on all platforms here in the issue tracker.
